spring:
  application:
    name: kafka
  # Spring整合Kafka
  kafka:
    # kafka服务地址，多个逗号分隔
    bootstrap-servers: 127.0.0.1:9092
    # 1、producer配置
    producer:
      # 1.1、发送消息失败重试次数
      retries: 1
      # 1.2、批量发送数据的配置
      batch-size: 16384
      # 1.3、设置kafka生产者内存缓冲区的大小，官方推荐32M。该配置配合1.2使用
      buffer-memory: 33554432
      # 1.4、kafka消息序列化配置
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 1.5、消息可靠性配置
      # acks=1：生产者发送消息后，只要leader partition接收并写入消息后，就可以响应给发送者，不关心replica的同步情况。可靠性99%，已经很高了，对应一般业务来说足够。
      # acks=0：生产者发送消息后，不需要等待任何broker的响应。可靠性最低，一般用于写日志的场景。
      # acks=-1或all：生产者发送消息后，需要等待ISR中的所有副本都成功写入消息后才能收到broker的响应信息。可靠性非常高.
      acks: 1
    # 2、consumer
    consumer:
      # 2.1、关闭自动commit
      enable-auto-commit: false
      # 2.2、从最近一次提交的offset开始拉取消息
      auto-offset-reset: earliest
      # 2.3、反序列化
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # 2.4、启用手动签收
      ack-mode: manual
      # 2.5、listener允许几个线程并行
      concurrency: 5
server:
  port: 8080
